services:
  database:
    image: postgres:17-alpine
    hostname: ${POSTGRES_HOST}
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '8001:${POSTGRES_PORT}'
    volumes:
      - database:/var/lib/postgresql/data

  test_db:
    image: postgres:17-alpine
    hostname: ${TEST_POSTGRES_HOST}
    container_name: test_database
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_HOST=${TEST_POSTGRES_HOST}
      - POSTGRES_PORT=${TEST_POSTGRES_PORT}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${TEST_POSTGRES_HOST_AUTH_METHOD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '8002:${TEST_POSTGRES_PORT}'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data



  redis:
    image: redis:8-alpine
    hostname: ${REDIS_HOST}
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  core:
    build:
      context: ../services/TODO-core
    env_file:
      - ../services/TODO-core/.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8010:8010'
    volumes:
      - ../services/TODO-core:/app
    command: >
      sh -c "
      python manage.py check --database default &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8010
      "

  authentication:
    build:
      context: ../services/authentication
    env_file:
      - ../services/authentication/.env
    ports:
      - '8000:8000'
    volumes:
      - ../services/authentication:/app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
      alembic upgrade heads &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  celery-worker:
    build:
      context: ../services/authentication
    env_file:
      - ../services/authentication/.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A tasks worker --loglevel=info

  celery-beat:
    build:
      context: ../services/authentication
    env_file:
      - ../services/authentication/.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A tasks beat --loglevel=info

volumes:
  database:
  postgres_test_data:
  redis_data:
